# Generated by Django 4.1 on 2022-10-10 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FemaleUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CID', models.IntegerField(unique=True)),
                ('Name', models.CharField(max_length=150)),
                ('DOB', models.DateTimeField()),
                ('Gender', models.CharField(default='Female', max_length=20)),
                ('Village', models.CharField(max_length=100)),
                ('Chiwog', models.CharField(max_length=100)),
                ('ThramNo', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('HouseHoldNo', models.CharField(max_length=100)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MaleUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CID', models.IntegerField(unique=True)),
                ('Name', models.CharField(max_length=150)),
                ('DOB', models.DateTimeField()),
                ('Gender', models.CharField(default='Male', max_length=20)),
                ('Village', models.CharField(max_length=100)),
                ('Chiwog', models.CharField(max_length=100)),
                ('ThramNo', models.CharField(max_length=100)),
                ('HouseHoldNo', models.CharField(max_length=100)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('contact_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tender_name', models.CharField(max_length=255)),
                ('Tender_Image', models.ImageField(upload_to='tender/')),
                ('Tender_description', models.CharField(max_length=255)),
                ('contact', models.IntegerField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_name', models.CharField(max_length=255)),
                ('vacancy_Image', models.ImageField(upload_to='tender/')),
                ('vacancy_description', models.CharField(max_length=255)),
                ('contact', models.IntegerField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MarriageID', models.CharField(max_length=100)),
                ('Marriage_certificate', models.ImageField(upload_to='image')),
                ('Spouce_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Spouce', to='crudapp.femaleuserdata', unique=True)),
                ('YOUR_CId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Your_CID', to='crudapp.maleuserdata', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChildData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Child_name', models.CharField(max_length=255)),
                ('DOB_child', models.DateField()),
                ('Marriage_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents_Marriage_ID', to='crudapp.marriage')),
            ],
        ),
    ]
