# Generated by Django 4.1 on 2022-10-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_alter_maleuserdata_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maleuserdata',
            name='Gender',
        ),
        migrations.AlterField(
            model_name='maleuserdata',
            name='profile',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='image'),
        ),
    ]
