# Generated by Django 4.1 on 2022-10-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_remove_maleuserdata_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maleuserdata',
            name='profile',
        ),
        migrations.AddField(
            model_name='maleuserdata',
            name='Gender',
            field=models.CharField(default='Male', max_length=20),
        ),
    ]
