# Generated by Django 4.1 on 2022-10-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0005_remove_maleuserdata_profile_maleuserdata_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='femaleuserdata',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='maleuserdata',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20),
        ),
    ]
