# Generated by Django 4.1 on 2022-10-22 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0007_maleuserdata_profile_alter_femaleuserdata_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marriage',
            name='Spouce_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Spouce', to='crudapp.femaleuserdata', unique=True),
        ),
    ]
